version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=FastApiApp
      - SECRET_KEY=78a63a0e12f5f8b2e4daacdc7193c6ebb3e75cfa162ded5f8f957f2b9e271d2f
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=FastApiApp
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
